[package]
name        = "mcpp-kaki"
version     = "1.0.0"
description = "A xianxia Metroidvania action game (Godot GDExtension)"
license     = "MIT"
repo        = "https://github.com/farna/mcpp-kaki"

[toolchain]
default = "llvm@22.1.8"

[language]
standard   = "c++23"
modules    = true
import_std = false

[build]
bmi_schedule = "off"
cflags = [
    "-DLINUX_ENABLED",
    "-DUNIX_ENABLED",
    "-DDEBUG_ENABLED",
]

include_dirs = [
    "src",
]

[modules]
sources = [
    "src/**/*.cppm",
    "src/**/*.cpp",
]
exports = ["mcpp_kaki.utils", "mcpp_kaki.combat", "mcpp_kaki.inventory", "mcpp_kaki.cultivation", "mcpp_kaki.nodes", "mcpp_kaki.core"]

[targets.mcpp-kaki]
kind   = "shared"
soname = "libmcpp-kaki.linux.template_debug.x86_64.so"

[dependencies.compat]
godot-cpp = "10.0.0-rc1"

[dependencies.godotengine]
godot-cpp-m = "10.0.0-rc1"
